name: main_CI
on:
  push:
    branches:
      - 'main'
# tst
jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      generator_changed: ${{ steps.filter.outputs.generator }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Check
        uses: dorny/paths-filter@v4
        id: filter
        with:
          filters: |
            generator:
              - 'task/docs/scripts/**'
              - 'task/docs/t2.md'
  build-test:
    needs: check-changes
    runs-on:
      ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v7
        with:
          ref: ${{ gitverse.ref_name }}

      - name: python_install
        uses: actions/setup-python@v7
        with:
          python-version: '3.14.3'
          cache: 'pip'
          cache-dependency-path: ./requirements.txt

      - name: requirements_install
        run: pip install -r requirements.txt

      - name: build_static
        run: |
          cd ./task 
          mkdocs build --strict

      - name: upload_artifacts
        uses: gitverse/upload-pages-artifact@v1.0.0
        with:
          path: ./task/site


  deploy-gh:
    needs: build-test
    runs-on:
      ubuntu-latest
    steps:
      - name: Deploy to Pages
        uses: gitverse/deploy-pages@v1.0.0


